# Generated by Django 4.1.3 on 2023-01-17 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_giriscikis'),
    ]

    operations = [
        migrations.CreateModel(
            name='GorevliLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gorevli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gorevli')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.lab')),
            ],
        ),
    ]
