# Generated by Django 4.1.3 on 2023-01-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_gorevlilab'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='gorevliler',
            field=models.ManyToManyField(to='app.gorevli'),
        ),
        migrations.DeleteModel(
            name='GorevliLab',
        ),
    ]
