# Generated by Django 4.1.5 on 2023-01-23 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_lab_gorevliler_delete_gorevlilab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giriscikis',
            name='tarih_saat',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lab',
            name='gorevliler',
            field=models.ManyToManyField(blank=True, to='app.gorevli'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='name',
            field=models.CharField(default=datetime.datetime.now, max_length=100),
        ),
    ]
