# Generated by Django 4.1.5 on 2023-01-23 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_giriscikis_tarih_saat_alter_lab_gorevliler_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='gorevliler',
        ),
        migrations.DeleteModel(
            name='girisCikis',
        ),
        migrations.DeleteModel(
            name='Gorevli',
        ),
        migrations.DeleteModel(
            name='lab',
        ),
    ]
