# Generated by Django 4.1.5 on 2023-01-23 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='gorevli',
        ),
        migrations.AddField(
            model_name='lab',
            name='sorumlu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
