# Generated by Django 4.1.5 on 2023-01-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_lab_gorevli_lab_sorumlu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gorevli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='lab',
            name='gorevli',
            field=models.ManyToManyField(blank=True, to='app.gorevli'),
        ),
    ]
