# Generated by Django 4.1.5 on 2023-01-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_sorumlu_delete_gorevli_alter_lab_gorevli_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='sorumlu',
            field=models.CharField(max_length=150),
        ),
        migrations.DeleteModel(
            name='Sorumlu',
        ),
    ]
