# Generated by Django 4.1.5 on 2023-01-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_lab_sorumlu_delete_sorumlu'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
