# Generated by Django 4.1.5 on 2023-01-24 12:43

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_lab_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gorevli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('tel_num', models.CharField(max_length=10)),
                ('cad_num', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='lab',
            name='sorumlu',
            field=models.CharField(max_length=150, verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AlterField(
            model_name='lab',
            name='gorevli',
            field=models.ManyToManyField(blank=True, to='app.gorevli'),
        ),
    ]
