# Generated by Django 4.1.5 on 2023-01-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_gorevli_alter_lab_sorumlu_alter_lab_gorevli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gorevli',
            name='email',
            field=models.EmailField(max_length=150),
        ),
    ]
