# Generated by Django 4.1.5 on 2023-01-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_gorevli_tel_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gorevli',
            name='tel_num',
            field=models.CharField(max_length=10),
        ),
    ]
