# Generated by Django 4.1.5 on 2023-01-24 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_gorevli_tel_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gorevli',
            name='tel_num',
        ),
    ]
