# Generated by Django 4.1.5 on 2023-01-26 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_lab_sorumlu_sorumlu'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zaman', models.DateTimeField(auto_now=True)),
                ('lab', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.lab')),
                ('lab_gorevli', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.gorevli')),
            ],
        ),
        migrations.CreateModel(
            name='LogIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zaman', models.DateTimeField(auto_now=True)),
                ('lab', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.lab')),
                ('lab_gorevli', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.gorevli')),
            ],
        ),
    ]
