# Generated by Django 4.1.5 on 2023-01-26 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_gorevli_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gorevli',
            name='image',
        ),
    ]
