# Generated by Django 4.1.5 on 2023-01-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_gorevli_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gorevli',
            name='image',
            field=models.ImageField(null=True, upload_to='lab'),
        ),
    ]
