# Generated by Django 4.1.5 on 2023-01-26 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_gorevli_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gorevli',
            old_name='cad_num',
            new_name='card_num',
        ),
    ]
