# Generated by Django 4.1.5 on 2023-01-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_rename_cad_num_gorevli_card_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gorevli',
            name='image',
            field=models.ImageField(upload_to='lab'),
        ),
    ]
