# Generated by Django 4.1.5 on 2023-03-06 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_gorevli_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gorevli',
            name='email',
            field=models.EmailField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='sorumlu',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.lab'),
        ),
    ]
