# Generated by Django 4.1.5 on 2023-03-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_gorevli_email_alter_sorumlu_lab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gorevli',
            name='card_num',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
