# Generated by Django 4.1.5 on 2023-03-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_gorevli_card_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='durum',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
